### ISSUE TITLE
purrr r package is required 

### ISSUE THREAD

**Issue by sharmavarun840** [NovembreLab/PCAviz#6]
While setting up PCAviz, sometime it Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘purrr’

install package  ("purrr") will help in right installation

**Comment by pcarbo** [comment]
@sharmavarun840 How are you installing PCAviz? PCAviz does not use the purrr package.

**Comment by sharmavarun840** [comment]
Hey, this package is very helpful, i found this error and solved it by installing "purrr"
following is the whole history of error and solution, you may check and do tell where I was wrong, I will appreciate it

> install.packages("devtools")
Installing package into ‘C:/Users/Admin/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  the 'wininet' method is deprecated for http:// and https:// URLs
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/devtools_2.4.4.zip'
Content type 'application/zip' length 429180 bytes (419 KB)
downloaded 419 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Admin\AppData\Local\Temp\RtmpWmLmLg\downloaded_packages
Warning message:
R graphics engine version 15 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed. 
> 
> devtools::install_github("NovembreLab/PCAviz",build_vignettes = TRUE)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘purrr’
> install.packages("purrr")
Installing package into ‘C:/Users/Admin/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  the 'wininet' method is deprecated for http:// and https:// URLs
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/purrr_0.3.5.zip'
Content type 'application/zip' length 410981 bytes (401 KB)
downloaded 401 KB

package ‘purrr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Admin\AppData\Local\Temp\RtmpWmLmLg\downloaded_packages
> devtools::install_github("NovembreLab/PCAviz",build_vignettes = TRUE)
Downloading GitHub repo NovembreLab/PCAviz@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                              
2: CRAN packages only               
3: None                             
4: lifecycle (1.0.2 -> 1.0.3) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
lazyeval    (NA    -> 0.2.2 ) [CRAN]
lifecycle   (1.0.2 -> 1.0.3 ) [CRAN]
curl        (NA    -> 4.3.3 ) [CRAN]
isoband     (NA    -> 0.2.6 ) [CRAN]
data.table  (NA    -> 1.14.2) [CRAN]
crosstalk   (NA    -> 1.2.0 ) [CRAN]
tidyr       (NA    -> 1.2.1 ) [CRAN]
plotly      (NA    -> 4.10.0) [CRAN]
maps        (NA    -> 3.4.0 ) [CRAN]
countrycode (NA    -> 1.4.0 ) [CRAN]
Installing 10 packages: lazyeval, lifecycle, curl, isoband, data.table, crosstalk, tidyr, plotly, maps, countrycode
Installing packages into ‘C:/Users/Admin/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/lazyeval_0.2.2.zip'
Content type 'application/zip' length 161543 bytes (157 KB)
downloaded 157 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/lifecycle_1.0.3.zip'
Content type 'application/zip' length 139000 bytes (135 KB)
downloaded 135 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/curl_4.3.3.zip'
Content type 'application/zip' length 2492421 bytes (2.4 MB)
downloaded 2.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/isoband_0.2.6.zip'
Content type 'application/zip' length 2180407 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/data.table_1.14.2.zip'
Content type 'application/zip' length 2243013 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/crosstalk_1.2.0.zip'
Content type 'application/zip' length 410221 bytes (400 KB)
downloaded 400 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/tidyr_1.2.1.zip'
Content type 'application/zip' length 967295 bytes (944 KB)
downloaded 944 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/plotly_4.10.0.zip'
Content type 'application/zip' length 3173742 bytes (3.0 MB)
downloaded 3.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/maps_3.4.0.zip'
Content type 'application/zip' length 3098539 bytes (3.0 MB)
downloaded 3.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/countrycode_1.4.0.zip'
Content type 'application/zip' length 1249942 bytes (1.2 MB)
downloaded 1.2 MB

package ‘lazyeval’ successfully unpacked and MD5 sums checked
package ‘lifecycle’ successfully unpacked and MD5 sums checked
package ‘curl’ successfully unpacked and MD5 sums checked
package ‘isoband’ successfully unpacked and MD5 sums checked
package ‘data.table’ successfully unpacked and MD5 sums checked
package ‘crosstalk’ successfully unpacked and MD5 sums checked
package ‘tidyr’ successfully unpacked and MD5 sums checked
package ‘plotly’ successfully unpacked and MD5 sums checked
package ‘maps’ successfully unpacked and MD5 sums checked
package ‘countrycode’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Admin\AppData\Local\Temp\RtmpWmLmLg\downloaded_packages
v  checking for file 'C:\Users\Admin\AppData\Local\Temp\RtmpWmLmLg\remotes1a9c10b94b30\NovembreLab-PCAviz-f5280bc/DESCRIPTION' ...
-  preparing 'PCAviz': (2.6s)
v  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes (2.9s)
v  creating vignettes (1m 8.2s)
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'PCAviz_0.3-37.tar.gz'
   
Installing package into ‘C:/Users/Admin/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package 'PCAviz' ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (PCAviz)
Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  the 'wininet' method is deprecated for http:// and https:// URLs
2: In download.file(url, destfile, method, mode = "wb", ...) :
  the 'wininet' method is deprecated for http:// and https:// URLs
3: In download.file(url, destfile, method, mode = "wb", ...) :
  the 'wininet' method is deprecated for http:// and https:// URLs
4: In download.file(url, destfile, method, mode = "wb", ...) :
  the 'wininet' method is deprecated for http:// and https:// URLs
5: In download.file(url, destfile, method, mode = "wb", ...) :
  the 'wininet' method is deprecated for http:// and https:// URLs
6: In download.file(url, destfile, method, mode = "wb", ...) :
  the 'wininet' method is deprecated for http:// and https:// URLs
7: In download.file(url, destfile, method, mode = "wb", ...) :
  the 'wininet' method is deprecated for http:// and https:// URLs
8: In download.file(url, destfile, method, mode = "wb", ...) :
  the 'wininet' method is deprecated for http:// and https:// URLs
9: In download.file(url, destfile, method, mode = "wb", ...) :
  the 'wininet' method is deprecated for http:// and https:// URLs
10: In download.file(url, destfile, method, mode = "wb", ...) :
  the 'wininet' method is deprecated for http:// and https:// URLs

**Comment by pcarbo** [comment]
@sharmavarun840 This issue appears to be specific to your R or RStudio setup. This works for me:
```r
devtools::install_github("NovembreLab/PCAviz",build_vignettes = TRUE)
```
I'll close this ticket but thank you for sharing your solution. Perhaps it will be helpful for others.
